spring:
  profiles:
    active: db,db-@env@
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000
  context-path: /moon
banner:
  charset: UTF-8