env: prod
spring:
  datasource:
    druid:
      db1:
        username: onepay_yuenan
        password: Zfjr83095520
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/pay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        username: onepay_yuenan
        password: Zfjr83095520
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/pay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        initialSize: 5
        minIdle: 5
        maxActive: 20